In [0]:
from keras.datasets import mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
print('x_train'+'='+ str(len(x_train)))
len(x_test)


Using TensorFlow backend.


11493376/11490434 [==============================] - 3s 0us/step
x_train=60000


10000

In [0]:
x_train=x_train.astype('float32')/225
x_test=x_test.astype('float32')/225

In [0]:
from keras.utils import np_utils
print(y_train[:10])
y_train=np_utils.to_categorical(y_train,10)
y_test=np_utils.to_categorical(y_test,10)
print(y_train[:10])

[5 0 4 1 9 2 1 3 1 4]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [0]:
# break training set into training and validation sets
(x_train, x_valid) = x_train[6000:], x_train[:6000]
(y_train, y_valid) = y_train[6000:], y_train[:6000]

# print shape of training set
print('x_train shape:', x_train.shape)

# print number of training, validation, and test images
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')
print(x_valid.shape[0], 'validation samples')

x_train shape: (54000, 28, 28)
54000 train samples
10000 test samples
6000 validation samples


In [0]:
x_valid.shape


(6000, 28, 28)

In [0]:
x_train=x_train.reshape((-1,28,28,1))
#y_train=y_train.reshape((-1,54000,10))
x_test=x_test.reshape((-1,28,28,1))
#y_test=y_test.reshape((-1,10000,10))
x_valid=x_valid.reshape((-1,28,28,1))
#y_valid=y_valid.reshape((-1,6000,10))

In [0]:
import pandas as pd
from google.colab import files


In [0]:
! pip install kaggle

    100% |████████████████████████████████| 51kB 4.0MB/s 
    100% |████████████████████████████████| 51kB 19.6MB/s 
  Running setup.py bdist_wheel for kaggle ... - \ done
  Stored in directory: /content/.cache/pip/wheels/40/3a/1a/030a08ebef5e1aef1ee6f0fd2b70666a9363f48d4bb6f7c4b4
Successfully built kaggle


In [0]:
!ls -a

.  ..  .cache  .config	datalab  .forever  .ipython  .keras  .local


In [0]:
!mkdir .kaggle

In [0]:
import json
token ={"username":"shiva2251","key":"1bab1b8c61c8fea8169be8aae72f3642"}
with open('/content/.kaggle/kaggle.json', 'w') as file:
    json.dump(token, file)

In [0]:
!chmod 600 /content/.kaggle/kaggle.json

In [0]:
!kaggle config set -n path -v{/content}

path is now set to: {/content}


In [0]:
!kaggle competitions download -c digit-recognizer -p/content

 83%|███████████████████████████████▋      | 61.0M/73.2M [00:00<00:00, 53.4MB/s]
100%|███████████████████████████████████████| 73.2M/73.2M [00:00<00:00, 104MB/s]
 98%|█████████████████████████████████████▍| 48.0M/48.8M [00:00<00:00, 76.3MB/s]
100%|███████████████████████████████████████| 48.8M/48.8M [00:00<00:00, 127MB/s]
  0%|                                                | 0.00/235k [00:00<?, ?B/s]
100%|█████████████████████████████████████████| 235k/235k [00:00<00:00, 140MB/s]


In [0]:
import pandas as pd
df = pd.read_csv('test.csv')
df.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [0]:
dff=df.values.astype('float32')/255
dff

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:

dff= dff.reshape(28000,28,28)
dff.shape

(28000, 28, 28)

In [0]:
dff=dff.reshape(-1,28,28,1)
dff.shape

(28000, 28, 28, 1)

In [0]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
model=Sequential()
model.add(Conv2D(filters=16,kernel_size=(2,2),padding='same',activation='relu',
                 input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=30,kernel_size=2,padding='same',activation='relu'))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=50,kernel_size=2,padding='same',activation='relu'))
model.add(MaxPooling2D(pool_size=2))
model.add(Dropout(0.3))
model.add(Flatten())
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.35))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(10,activation='softmax'))
          
          
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_12 (Conv2D)           (None, 28, 28, 16)        80        
_________________________________________________________________
max_pooling2d_12 (MaxPooling (None, 14, 14, 16)        0         
_________________________________________________________________
conv2d_13 (Conv2D)           (None, 14, 14, 30)        1950      
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 7, 7, 30)          0         
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 7, 7, 50)          6050      
_________________________________________________________________
max_pooling2d_14 (MaxPooling (None, 3, 3, 50)          0         
_________________________________________________________________
dropout_8 (Dropout)          (None, 3, 3, 50)          0         
__________

In [0]:
model.compile(loss='categorical_crossentropy',optimizer='rmsprop',metrics=['accuracy'])

In [0]:
from keras.callbacks import ModelCheckpoint
checkpointer=ModelCheckpoint(filepath='model_weights_best.hdf5',verbose=1,save_best_only=True)
hist=model.fit(x_train,y_train,batch_size=419,epochs=9,validation_data=(x_valid,y_valid),callbacks=[checkpointer],verbose=2,shuffle=True)

Train on 54000 samples, validate on 6000 samples
Epoch 1/9
 - 4s - loss: 0.2936 - acc: 0.9565 - val_loss: 0.1117 - val_acc: 0.9760

Epoch 00001: val_loss improved from inf to 0.11170, saving model to model_weights_best.hdf5
Epoch 2/9
 - 4s - loss: 0.2782 - acc: 0.9551 - val_loss: 0.0923 - val_acc: 0.9823

Epoch 00002: val_loss improved from 0.11170 to 0.09232, saving model to model_weights_best.hdf5
Epoch 3/9
 - 4s - loss: 0.3285 - acc: 0.9522 - val_loss: 0.1337 - val_acc: 0.9743

Epoch 00003: val_loss did not improve from 0.09232
Epoch 4/9
 - 4s - loss: 0.2871 - acc: 0.9545 - val_loss: 0.1111 - val_acc: 0.9808

Epoch 00004: val_loss did not improve from 0.09232
Epoch 5/9
 - 4s - loss: 0.4083 - acc: 0.9470 - val_loss: 0.1399 - val_acc: 0.9732

Epoch 00005: val_loss did not improve from 0.09232
Epoch 6/9
 - 4s - loss: 0.6685 - acc: 0.9075 - val_loss: 0.1379 - val_acc: 0.9727

Epoch 00006: val_loss did not improve from 0.09232
Epoch 7/9
 - 4s - loss: 0.9027 - acc: 0.9117 - val_loss: 0.23

In [0]:
model.load_weights('model_weights_best.hdf5')

In [0]:
score=model.evaluate(x_test,y_test,verbose=0)
score[1]

0.9822

In [0]:
predic=model.predict_classes(dff,verbose=0)
predic

array([2, 0, 9, ..., 3, 9, 2])

In [0]:
predic.shape
#99.27-3

(28000,)

In [0]:
pd.DataFrame({'ImageId':list(range(1,len(predic)+1)),'Label':predic.astype(int)}).set_index('ImageId').to_csv('Kagg_digit_recog_cnn8.csv')

In [0]:
from google.colab import files

In [0]:
!ls -a

.	  Kagg_digit_recog_cnn3.csv  .keras
..	  Kagg_digit_recog_cnn4.csv  .local
.cache	  Kagg_digit_recog_cnn5.csv  model_weights_best.hdf5
.config   Kagg_digit_recog_cnn6.csv  .nv
datalab   Kagg_digit_recog_cnn7.csv  sample_submission.csv
.forever  Kagg_digit_recog_cnn8.csv  test.csv
.ipython  .kaggle		     train.csv


In [0]:
!kaggle competitions submit -c digit-recognizer -f Kagg_digit_recog_cnn7.csv -m'SUB_7'

Successfully submitted to Digit Recognizer

In [0]:
files.download('Kagg_digit_recog_cnn3.csv')